- name: Configure service
  hosts: all
  vars_files:
    - ../group_vars/all/vars.yml
    - ../group_vars/all/vault.yml
  tasks:
    - name: Service API
      ansible.builtin.debug:
        msg: "API Key: {{ api_key }}"
